pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION    = "us-east-1"
        KUBECONFIG            = "${WORKSPACE}/kubeconfig"
    }
    stages {
        stage("Create an EKS Cluster") {
            steps {
                dir('projects/deployK8Application/eks') {
                    sh 'terraform init'
                    sh 'terraform plan'
                    sh 'terraform apply -auto-approve'
                }
            }
        }
        stage("Deploy to EKS") {
            steps {
                dir('projects/deployK8Application/kubernetes') {
                    sh '''
                        export PATH=/usr/local/bin:$PATH
                        aws --version
                        kubectl version --client
                        aws eks update-kubeconfig --name jenkins-eks-cluster --region $AWS_DEFAULT_REGION --kubeconfig $KUBECONFIG
                        kubectl apply -f nginx-deployment.yaml
                        kubectl delete service nginx --ignore-not-found
                        kubectl apply -f nginx-service.yaml
                    '''
                }
            }
        }
    }
}
