---
apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
spec:
  type: NodePort
  selector:
    app: myapp
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080