#!/usr/bin/env groovy
pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION    = "us-east-1"
        KUBECONFIG            = "${WORKSPACE}/kubeconfig"
    }
    stages {
        stage("Validate AWS Access") {
            steps {
                script {
                    dir('projects/deployK8Application/eks') {
                        sh 'aws sts get-caller-identity'
                        sh 'aws eks list-clusters'
                    }
                }
            }
        }
        stage("Destroy EKS Cluster") {
            steps {
                script {
                    dir('projects/deployK8Application/eks') {
                        sh 'terraform init'
                        sh 'terraform destroy -auto-approve -var="cluster_name=jenkins-eks-cluster"'
                    }
                }
            }
        }
    }
}